version: "2"
services:
  app:
    hostname: app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
    - '${DEV_LOOPBACK_IP}:22:22'
    working_dir: /app
    command: "bash start-with-sshd.sh"
    volumes:
    - .:/app
